AWSTemplateFormatVersion: 2010-09-09
Description: 'This template updates the specified route tables & security groups to allow communications via the VPC peering connection ship-planner-infra-to-dev.'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Name
        Parameters:
          - EnvironmentName
      - Label:
          default: Network Configuration
        Parameters:
          - RouteTableIds
          - NumberOfRouteTables
      - Label:
          default: VPC Peering Configuration
        Parameters:
          - PeerName
          - PeerVPCCIDR
    ParameterLabels:
      EnvironmentName:
        default: An environment name that will be prefixed to resource names
      NumberOfRouteTables:
        default: Number of Route Tables
      PeerName:
        default: Peer Name
      PeerVPCCIDR:
        default: Peer VPC CIDR
      RouteTableIds:
        default: Route Table IDs
      VPCPeeringConnectionId:
        default: VPC Peering Connection ID

Parameters:

  EnvironmentName:
    Description: 'An environment name that will be prefixed to resource names'
    Type: String
    Default: ship-planner-update-dev-to-infra-route

  VPCPeerengStackName:
    Description: 'Name of an active CloudFormation stack that contains the networking
      resources, such as the peereng conection, that will be used in this
      stack.'
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: ship-planner-infra-to-dev-peereng # ship-planner-infra-to-dev-peereng PeerName

  VPCPeerengSecurityGtoupStackName:
    Description: 'Name of an active CloudFormation stack that contains the ship-planner-vpc-peereng-dev-sg
      resources, such as the ship-planner-vpc-peereng-dev-sg, that will be used in this
      stack.'
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: ship-planner-vpc-peereng-dev-sg # ship-planner-vpc-peereng-dev-sg EnvironmentName

  VPCDevStackName:
    Description: 'Name of an active CloudFormation stack that contains the ship-planner-dev-vpc
      resources, such as the ship-planner-dev-vpc, that will be used in this
      stack.'
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: ship-planner-dev-vpc # ship-planner-dev-vpc EnvironmentName

  NumberOfRouteTables:
    AllowedValues: [ 1, 2, 3, 4, 5, 6 ]
    Description: 'Number of Route Table IDs to update. This must match your items in the comma-separated list of RouteTableIds parameter without space.'
    Type: String
    Default: 2

  PeerName:
    Description: 'Name of the VPC Peer'
    MaxLength: 255
    Type: String
    Default: ship-planner-infra-to-dev-peereng

  PeerVPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: 'CIDR of the VPC Infra Peer'
    Type: String
    Default: 172.16.0.0/16

Resources:

  PeerRoutePublicRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: ${VPCDevStackName}-PublicRouteTable # from ship-planner-vpc.yaml  PublicRouteTable output export
      DestinationCidrBlock: !Ref PeerVPCCIDR
      VpcPeeringConnectionId:
        Fn::ImportValue:
          Fn::Sub: ${VPCPeerengStackName}-VPCPeeringConnection # from vpc-peering-connection.yaml  VPCPeeringConnectionId output export

  PeerRoutePrivateRouteTable:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Fn::ImportValue:
          Fn::Sub: ${VPCDevStackName}-PrivateRouteTable # from ship-planner-vpc.yaml  PrivateRouteTable output export
      DestinationCidrBlock: !Ref PeerVPCCIDR
      VpcPeeringConnectionId:
        Fn::ImportValue:
          Fn::Sub: ${VPCPeerengStackName}-VPCPeeringConnection # from vpc-peering-connection.yaml  VPCPeeringConnectionId output export

  PeerIngressRule:
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W42
            reason: Allow all inbound communications from VPC Peer CIDR
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: '-1'
      Description: !Sub Allow All Inbound Communications from VPC Peer, ${PeerName}
      GroupId:
        Fn::ImportValue:
          Fn::Sub: ${VPCPeerengSecurityGtoupStackName}-AWSVPCPeerengAllTrafficSecurityGroup
      CidrIp: !Ref PeerVPCCIDR
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName