AWSTemplateFormatVersion: 2010-09-09
Description: 'This templates creates a VPC Peering connection. (Requester Account ship-planner-infra-to-test)'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VPCID
      - Label:
          default: VPC Peering Configuration
        Parameters:
          - PeerName
          - PeerOwnerId
          - PeerVPCID
    ParameterLabels:
      PeerName:
        default: Peer Name
      PeerOwnerId:
        default: Peer Owner ID
      PeerVPCID:
        default: Peer VPC ID
      VPCID:
        default: VPC ID

Parameters:

  VPCAccepterStackName:
    Description: 'Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC for ship-planner-test, that will be used in this
      stack.'
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: ship-planner-test-vpc # from ship-planner-test EnvironmentName

  VPCRequesterStackName:
    Description: 'Name of an active CloudFormation stack that contains the networking
      resources, such as the VPC for ship-planner-test-vpc, that will be used in this
      stack.'
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: "^[a-zA-Z][-a-zA-Z0-9]*$"
    Default: ship-planner-infra-vpc # from ship-planner-vpc.yaml sship-planner-infra-vpc EnvironmentName

  PeerName:
    Description: Name of the VPC Peer
    MaxLength: 255
    Type: String
    Default: ship-planner-infra-to-test-peereng

Resources:
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId:
        Fn::ImportValue:
          Fn::Sub: ${VPCRequesterStackName}-VPC # from ship-planner-test-vpc
      PeerVpcId:
        Fn::ImportValue:
          Fn::Sub: ${VPCAccepterStackName}-VPC # from ship-planner-test-vpc
      PeerOwnerId:
        Fn::ImportValue:
          Fn::Sub: ${VPCAccepterStackName}-VPCAccountId # from ship-planner-test-vpc
      Tags:
        - Key: Name
          Value: !Ref PeerName

Outputs:
  VPCPeeringConnectionId:
    Description: VPC Peering Connection ID
    Value: !Ref VPCPeeringConnection
    Export:
      Name:
        Fn::Sub: ${AWS::StackName}-VPCPeeringConnection # to vpc-peering-updates-route-test.yaml & vpc-peering-updates-route-infra.yaml