name: Create infra Envirovement

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: true
        default: "eu-central-1"
      KeyName:
        description: "Name of key for Bastion Host and Pritunl VPN"
        required: true
        default: pritunl
      S3Name:
        description: "Name of S3 bucket for Pritunl VPN"
        required: true
        default: ship-planner-pritunl-secret

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cfn-deployment:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region }}

      # Create Stack for Ship Planner VPC infra cloudformation/VPC/my-apricot-vpc.yaml
      - name: Deploy Ship Planner VPC infra
        id: my-apricot-vps-infra
        run: |
          aws cloudformation deploy --stack-name ship-planner-infra-vpc \
            --template-file cloudformation/VPC/infra-vpc/ship-planner-vpc.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Create Stack for Ship Planner Pritunl Security Group cloudformation/security-groups/EC2/infra-sg/pritunl-sg.yaml
      - name: Deploy Ship Planner Pritunl VPN Security Group
        id: ship-planner-pritunl-security-group
        run: |
          aws cloudformation deploy --stack-name ship-planner-pritunl-vpn-sg \
            --template-file cloudformation/security-groups/EC2/infra-sg/pritunl-sg.yaml \
            --capabilities CAPABILITY_NAMED_IAM

      # Create Stack for Ship Planner Pritunl cloudformation/EC2/infra/VPN/pritunl.yaml
      - name: Deploy Ship Planner Pritunl VPN
        id: ship-planner-pritunl-vpn
        run: |
          aws cloudformation deploy --stack-name ship-planner-pritunl-vpn \
            --template-file cloudformation/EC2/infra/VPN/pritunl.yaml \
            --parameter-overrides KeyName=${{ github.event.inputs.KeyName }} S3Name=${{ github.event.inputs.S3Name }} \
            --capabilities CAPABILITY_NAMED_IAM